# Generated by Django 4.0.4 on 2022-05-17 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculos', '0001_initial'),
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(auto_now=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tiempo_estacionado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fin_mes', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_de_salida', models.BooleanField(blank=True, default=False, null=True)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Cuenta_Por_Cobrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registros.registro_pago')),
                ('a_cargo_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.area')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
