# Generated by Django 4.0.4 on 2022-05-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_entrada',
            old_name='Cuenta_Por_Cobrar',
            new_name='cuenta_Por_Cobrar',
        ),
    ]
