# Generated by Django 4.0.4 on 2022-05-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_rename_cuenta_por_cobrar_registro_entrada_cuenta_por_cobrar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_entrada',
            old_name='cuenta_Por_Cobrar',
            new_name='cuenta_por_cobrar',
        ),
    ]
